language: ruby
rvm:
- 2.1.3
gemfile:
- Gemfile
script: bundle exec jekyll build
notifications:
  slack:
    secure: eC2MUNsrzl1BF7WU9JAArWM34EZL2Sq8rLAKeTfLeGYBjuUQfXGEh2RK/KZ5IF/6mZsQz8q82mTkBR8LSmQTKAxucd4zE73S0f7MuOun2W0ytF9tDjVvmze7SPQJL5SCcx3TvwQo7NMjzf0foE43UVyq0e8by2RWcYeIXb1QyXc=
