project:
  type: website

website:
  title: "NSIDC Technical Blog"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/nsidc
      - icon: twitter
        href: https://twitter.com/NSIDC
format:
  html:
    theme: cosmo
    css: styles.css



