project:
  type: "website"

website:
  title: "NSIDC"
  navbar:
    right:
      - icon: "github"
        href: "https://github.com/nsidc"
      - icon: "twitter"
        href: "https://twitter.com/NSIDC"
format:
  html:
    theme: 
      light: ["flatly", "default"]
      dark: ["darkly", "default"]
    css: "styles.css"
